### ISSUE TITLE
Trailing white spaces after variable names are not stripped

### ISSUE THREAD

**Issue by TobiasBaeumlin** [c2r0b/vnmsim#10]
Minimal example:

LOD #1
STO X 
HLT

If there is a space after the variable name 'X ' it is interpreted as a new variable
![Screenshot_20220118_124354](https://user-images.githubusercontent.com/840090/149931421-9f0809b3-45c3-4cef-b17c-0dfc83525cf3.png)
.

**Comment by c2r0b** [comment]
This issue has been solved in the new version available [here](https://vnmsim.vercel.app/).
Thank you
