### ISSUE TITLE
Add french translation

### ISSUE THREAD

**Issue by benabel** [c2r0b/vnmsim#14]
Hello and thanks for this really nice simulator,

I would like to translate to french, should I edit the `locale.js` file or is there any tool that generates this file from another UI(transifex or other).

**Comment by c2r0b** [comment]
There is not an official tool for translations at the moment.
You are welcome to edit `locale.js` and then add the newly added language in the `languageOptions` list you find in `src/app/modals/settings.tsx`.

Thanks 🙏

**Comment by c2r0b** [comment]
You can submit a translation using Transifex: [transifex.com/lorenzo-ganni/vnmsim](https://www.transifex.com/lorenzo-ganni/vnmsim/)

Thanks

**Comment by c2r0b** [comment]
There is no french translation yet. I think Transifex blocked your translation request.
@benabel can you try again now?
