### ISSUE TITLE
Colouring decoder and buses

### ISSUE THREAD

**Issue by solitone** [c2r0b/vnmsim#3]
Hi, first of all, thank you for this beautiful simulator. I remember using the old PIP machine which needed Flash if I'm correct, and it was a real pain.

Here I don't report a real issue but rather a couple of suggestions. 

First, similar to the older Zanichelli version, I would turn on the decoder box before the ALU is instructed with the needed operation (+, =, etc.). This would clear up when the decode phase takes place. 

Second, it would be great help to turn on the address bus when a memory cell/variable is activated, and the data bus when an instruction/piece of data is read or stored.

Cheers

**Comment by lorenzoganni** [comment]
I'll try to work more on this project in the months to come to add lots of new features, in doing that I'll remember your suggestions for sure.

Thank you very much for your feedback!

**Comment by c2r0b** [comment]
The decoder box is now turned on before the ALU operation is evaluated
