### ISSUE TITLE
DIV is not working properly

### ISSUE THREAD

**Issue by manuelmatarueda** [c2r0b/vnmsim#34]
Hello the DIV command is returning a real number with decimals, whilest it should return only integer part. This makes that some of the samples and exercises doesn't work in the right way. Please fix it, then everything should work Ok.

For example the even sample for 5 is doing 5 / 2 = 2.5 then 5 * 2.5 = 5 then 5 - 5 = 0 and returning it is even what is not correct.

Thanks.

**Comment by c2r0b** [comment]
Fixed. Thanks!
