### ISSUE TITLE
Problems Writing the code in Safari.

### ISSUE THREAD

**Issue by lucadiliello** [c2r0b/vnmsim#4]
I'm running Mac OS 10.14.1 and Safari 12.0.1. When I try to write some instructions in the Code section, I cannot write more than 1 character per line. Moreover, I'm not able to insert a custom number in the memory variables because Safari does not let me do this.

**Comment by lorenzoganni** [comment]
I was able to replicate your issue and it appears to be a problem with the ACE Editor I'm using for the simulator code section. I'll try to fix these compatibility issues as soon as I can, in the meantime using Chrome or Firefox should avoid the issue.
Thank you!

**Comment by c2r0b** [comment]
For the time being I want to continue supporting only Chrome and Firefox last versons.
A partial rewrite is planned for when I'll have enough time for that.
Still Safari support is not in the plans, therefore I'm closing this issue for now.
