### ISSUE TITLE
Unavailable website simulator

### ISSUE THREAD

**Issue by TranquiloTech** [c2r0b/vnmsim#5]
Hello,

Please verify what's happening with the http://vnsimulator.altervista.org/ website. It seems not working properly from yesterday (08-27-2020).

If you could turn available a version already compiled to run in html or similar and/or to run directly in windows machines, I appreciate.

Looking to here from you as soon as possible! Thanks!

Regards

**Comment by c2r0b** [comment]
I restored the website, it should be working now. 
Thanks for opening an issue about that!

I'm thinking about turning this project into an electron app, but it needs some updating first. 
Hope I'll have the time for that soon.

**Comment by allewwaly** [comment]
The website menu doesn't display normally, please check that. Thanks!

**Comment by c2r0b** [comment]
Could you elaborate on what you mean please?
