### ISSUE TITLE
Single Iteration highlighting

### ISSUE THREAD

**Issue by mikebarkmin** [c2r0b/vnmsim#55]
I think that the wrong line is highlighted when running the program with single iterations.

![Bildschirmfoto vom 2024-04-11 08-28-11](https://github.com/c2r0b/vnmsim/assets/2592379/a405392e-07c8-40a9-9ed5-8fba69ade45e)

**Comment by c2r0b** [comment]
The issue should now be fixed ([vnmsim.app](https://vnmsim.app/))
Thank you @mikebarkmin
