### ISSUE TITLE
Adressing a "cell"

### ISSUE THREAD

**Issue by WalBrig** [c2r0b/vnmsim#6]
Hi all
I'm going to evaluate VNMS as a tool for education...

When I look at the different ewxamples and compare this with the short instruction section it shoul be possible to address a cell, e.g. in a "LOD cell/var" - statement. But, I'm wondering how one can address a cell? A variable is clear: "LOD x", but how is the syntax to access/load an cell ?

Thxs Walter

**Comment by c2r0b** [comment]
Hi,
it is not possible to access a memory cell from another one. For design reasons the memory and the variables are meant to be separated, but loading a memory cell could certainly become something to add (maybe optionally).
This repository is not actively maintained anymore, but hopefully it will be again soon and I will look into implementing this feature.

Thank you for opening this issue!

**Comment by WalBrig** [comment]
well, thx

so that means we do not have a vNSM but an Harvard Machine Simulator... quite simple -  it's a pity...
