### ISSUE TITLE
Real single step

### ISSUE THREAD

**Issue by danielhofer** [c2r0b/vnmsim#7]
Hi
i't not an issue but a wish:-)
For teaching reasons it would be great that I can click through all single steps with a mouse click.
When I click on "single step" the program will proceed a whole single step (load from RAM, decode, calculate and store in accumulator), but often it would be easier to demonstrate and work with students, if there is a feature to click for every step above: click for loading from RAM, click for decode, and so on.

Thanks a lot!
Daniel

**Comment by c2r0b** [comment]
Hi,
this is certainly a small addition that could be useful. 
This repository is not actively maintained anymore, but hopefully it will be again soon and I will look into implementing this feature.
In the meantime I encourage using the "Pause" button to achieve the same result.

Thank you for opening this issue!

**Comment by c2r0b** [comment]
This feature has been implemented in the new version available [here](https://vnmsim.vercel.app/).

<img width="226" alt="Screenshot 2022-10-09 at 18 24 47" src="https://user-images.githubusercontent.com/3254315/194768164-29a5c275-d6dc-4851-bdd6-3a94cf4ee9bb.png">

Thank you
